services:
  - type: web
    name: tribal-education-backend
    env: node
    region: singapore
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_CONFIG
        sync: false
    healthCheckPath: /api/health
